"""empty message

Revision ID: 1d9adcd77169
Revises: e4993473b0ac
Create Date: 2023-12-15 19:24:52.354819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9adcd77169'
down_revision = 'e4993473b0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Username', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_jedi', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_jedi')
        batch_op.drop_column('Username')

    # ### end Alembic commands ###
