"""empty message

Revision ID: 62904f5679af
Revises: e809b7611915
Create Date: 2023-12-18 16:32:27.738204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62904f5679af'
down_revision = 'e809b7611915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favs_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favs_characters_characters_id_key', type_='unique')
        batch_op.drop_constraint('favs_characters_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favs_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('favs_characters_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('favs_characters_characters_id_key', ['characters_id'])

    # ### end Alembic commands ###
